use_frameworks!

target 'ReceiptScan_Example' do
  pod 'ReceiptScan', :path => '../'

  target 'ReceiptScan_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
